1.0.0

diff --git a/scripts/valhalla_build_timezones b/scripts/valhalla_build_timezones
--- a/scripts/valhalla_build_timezones
+++ b/scripts/valhalla_build_timezones
@@ -2,32 +2,36 @@
 
 set -e  # Exit immediately if a command exits with a non-zero status
 
+timezones_folder=./timezones
+timezones_zip_file=timezones-with-oceans.shapefile.zip
+timezones_file_name=combined-shapefile-with-oceans
+
 if [ "$1" = "-f" ]; then
-  rm -rf ./timezones-with-oceans.shapefile.zip
+  rm -rf ${timezones_folder}/${timezones_zip_file}
 
-  echo 'Downloading timezone polygon file "timezones-with-oceans.shapefile.zip"...' 1>&2
+  echo 'Downloading timezone polygon file...' 1>&2
 
-  wget --quiet https://github.com/evansiroky/timezone-boundary-builder/releases/download/2024a/timezones-with-oceans.shapefile.zip 1>&2 || exit 1
+  wget --quiet https://github.com/evansiroky/timezone-boundary-builder/releases/download/2024a/${timezones_zip_file} -P ${timezones_folder} 1>&2 || exit 1
 else
-  if [ ! -f ./timezones-with-oceans.shapefile.zip ]; then
-    echo 'Timezone polygon file "timezones-with-oceans.shapefile.zip" is not found' 1>&2
+  if [ ! -f "${timezones_folder}/${timezones_zip_file}" ]; then
+    echo 'Timezone polygon file is not found' 1>&2
 
     exit 1
   fi
 fi
 
-echo 'Unzip timezone polygon file "timezones-with-oceans.shapefile.zip"...' 1>&2
+echo 'Unzip timezone polygon file...' 1>&2
 
-unzip -o ./timezones-with-oceans.shapefile.zip -d ./timezones-with-oceans 1>/dev/null || exit 1
+unzip -o ${timezones_folder}/${timezones_zip_file} 1>/dev/null || exit 1
 
 echo "Create spatial database..." 1>&2
 
 tz_file=$(mktemp)
-spatialite_tool -i -shp ./timezones-with-oceans/combined-shapefile-with-oceans -d ${tz_file} -t tz_world -s 4326 -g geom -c UTF-8 1>/dev/null || exit 1
+spatialite_tool -i -shp ${timezones_folder}/${timezones_zip_file}/${timezones_file_name} -d ${tz_file} -t tz_world -s 4326 -g geom -c UTF-8 1>/dev/null || exit 1
 spatialite ${tz_file} "SELECT CreateSpatialIndex('tz_world', 'geom');" 1>&2 || exit 1
 spatialite ${tz_file} "VACUUM;" 1>/dev/null || exit 1
 spatialite ${tz_file} "ANALYZE;" 1>/dev/null || exit 1
 
-rm -rf ./timezones-with-oceans
+rm -rf ${timezones_folder}/${timezones_file_name}*
 
 cat ${tz_file}
